import SwiftUI

let brandDomains: [String: String] = [
    // Music & Audio
    "spotify": "spotify.com",
    "spotify premium": "spotify.com",
    "apple music": "apple.com",
    "tidal": "tidal.com",
    "soundcloud": "soundcloud.com",
    "audible": "audible.com",
    "pandora": "pandora.com",
    "deezer": "deezer.com",
    "amazon music": "amazon.com",
    "youtube music": "youtube.com",
    "iheartradio": "iheart.com",
    "sirius xm": "siriusxm.com",
    "siriusxm": "siriusxm.com",

    // Video Streaming
    "netflix": "netflix.com",
    "hulu": "hulu.com",
    "disney": "disneyplus.com",
    "disney+": "disneyplus.com",
    "disneyplus": "disneyplus.com",
    "hbo": "max.com",
    "hbo max": "max.com",
    "max": "max.com",
    "amazon prime": "amazon.com",
    "prime video": "amazon.com",
    "youtube": "youtube.com",
    "youtube premium": "youtube.com",
    "youtube tv": "tv.youtube.com",
    "peacock": "peacocktv.com",
    "paramount": "paramountplus.com",
    "paramount+": "paramountplus.com",
    "crunchyroll": "crunchyroll.com",
    "funimation": "funimation.com",
    "apple tv": "apple.com",
    "apple tv+": "apple.com",
    "appletv": "apple.com",
    "discovery+": "discoveryplus.com",
    "espn": "espn.com",
    "espn+": "espn.com",
    "fubo": "fubo.tv",
    "fubotv": "fubo.tv",
    "sling": "sling.com",
    "sling tv": "sling.com",
    "philo": "philo.com",
    "plex": "plex.tv",
    "mubi": "mubi.com",
    "criterion": "criterionchannel.com",
    "shudder": "shudder.com",
    "amc+": "amcplus.com",
    "britbox": "britbox.com",
    "acorn tv": "acorn.tv",
    "starz": "starz.com",
    "showtime": "showtime.com",
    "cinemax": "cinemax.com",

    // Cloud & Storage
    "icloud": "apple.com",
    "google one": "one.google.com",
    "dropbox": "dropbox.com",
    "onedrive": "microsoft.com",
    "box": "box.com",
    "backblaze": "backblaze.com",
    "mega": "mega.io",
    "pcloud": "pcloud.com",
    "sync": "sync.com",

    // Productivity & Work
    "notion": "notion.so",
    "slack": "slack.com",
    "zoom": "zoom.us",
    "figma": "figma.com",
    "github": "github.com",
    "gitlab": "gitlab.com",
    "linear": "linear.app",
    "microsoft": "microsoft.com",
    "office 365": "microsoft.com",
    "office": "microsoft.com",
    "microsoft 365": "microsoft.com",
    "adobe": "adobe.com",
    "adobe creative cloud": "adobe.com",
    "creative cloud": "adobe.com",
    "asana": "asana.com",
    "trello": "trello.com",
    "jira": "atlassian.com",
    "atlassian": "atlassian.com",
    "confluence": "atlassian.com",
    "monday": "monday.com",
    "monday.com": "monday.com",
    "clickup": "clickup.com",
    "airtable": "airtable.com",
    "miro": "miro.com",
    "webflow": "webflow.com",
    "squarespace": "squarespace.com",
    "wix": "wix.com",
    "wordpress": "wordpress.com",
    "shopify": "shopify.com",
    "canva": "canva.com",
    "sketch": "sketch.com",
    "invision": "invisionapp.com",
    "loom": "loom.com",
    "grammarly": "grammarly.com",
    "typeform": "typeform.com",
    "mailchimp": "mailchimp.com",
    "hubspot": "hubspot.com",
    "salesforce": "salesforce.com",
    "intercom": "intercom.com",
    "zendesk": "zendesk.com",
    "freshdesk": "freshdesk.com",

    // Gaming
    "steam": "store.steampowered.com",
    "steam store": "store.steampowered.com",
    "xbox": "xbox.com",
    "xbox game pass": "xbox.com",
    "playstation": "playstation.com",
    "ps plus": "playstation.com",
    "playstation plus": "playstation.com",
    "psn": "playstation.com",
    "nintendo": "nintendo.com",
    "nintendo switch": "nintendo.com",
    "nintendo online": "nintendo.com",
    "twitch": "twitch.tv",
    "discord": "discord.com",
    "epic games": "epicgames.com",
    "ea play": "ea.com",
    "origin": "ea.com",
    "ubisoft": "ubisoft.com",
    "battle.net": "blizzard.com",
    "blizzard": "blizzard.com",
    "roblox": "roblox.com",
    "minecraft": "minecraft.net",
    "riot games": "riotgames.com",
    "gog": "gog.com",
    "humble bundle": "humblebundle.com",

    // Food & Coffee
    "starbucks": "starbucks.com",
    "dunkin": "dunkindonuts.com",
    "dunkin donuts": "dunkindonuts.com",
    "dunkin'": "dunkindonuts.com",
    "mcdonald's": "mcdonalds.com",
    "mcdonalds": "mcdonalds.com",
    "chick-fil-a": "chick-fil-a.com",
    "chickfila": "chick-fil-a.com",
    "subway": "subway.com",
    "domino's": "dominos.com",
    "dominos": "dominos.com",
    "pizza hut": "pizzahut.com",
    "panera": "panerabread.com",
    "panera bread": "panerabread.com",
    "shake shack": "shakeshack.com",
    "in-n-out": "in-n-out.com",
    "chipotle": "chipotle.com",
    "sweetgreen": "sweetgreen.com",
    "sweetgreen salads": "sweetgreen.com",
    "taco bell": "tacobell.com",
    "tacobell": "tacobell.com",
    "wendy's": "wendys.com",
    "wendys": "wendys.com",
    "burger king": "burgerking.com",
    "burgerking": "burgerking.com",
    "five guys": "fiveguys.com",
    "fiveguys": "fiveguys.com",
    "wingstop": "wingstop.com",
    "raising cane's": "raisingcanes.com",
    "raising canes": "raisingcanes.com",
    "panda express": "pandaexpress.com",
    "olive garden": "olivegarden.com",
    "applebee's": "applebees.com",
    "applebees": "applebees.com",
    "chilis": "chilis.com",
    "chili's": "chilis.com",
    "outback": "outback.com",
    "red lobster": "redlobster.com",
    "ihop": "ihop.com",
    "denny's": "dennys.com",
    "dennys": "dennys.com",
    "waffle house": "wafflehouse.com",
    "ritual coffee": "ritualcoffee.com",
    "ritual": "ritualcoffee.com",
    "blue bottle": "bluebottlecoffee.com",
    "blue bottle coffee": "bluebottlecoffee.com",
    "peet's": "peets.com",
    "peets": "peets.com",
    "peet's coffee": "peets.com",
    "dutch bros": "dutchbros.com",
    "philz": "philzcoffee.com",
    "philz coffee": "philzcoffee.com",

    // Food Delivery
    "doordash": "doordash.com",
    "uber eats": "ubereats.com",
    "grubhub": "grubhub.com",
    "instacart": "instacart.com",
    "postmates": "postmates.com",
    "caviar": "trycaviar.com",
    "seamless": "seamless.com",
    "gopuff": "gopuff.com",
    "weee": "sayweee.com",

    // Groceries
    "trader joe's": "traderjoes.com",
    "trader joes": "traderjoes.com",
    "whole foods": "wholefoodsmarket.com",
    "wholefoods": "wholefoodsmarket.com",
    "kroger": "kroger.com",
    "safeway": "safeway.com",
    "albertsons": "albertsons.com",
    "publix": "publix.com",
    "costco": "costco.com",
    "sam's club": "samsclub.com",
    "sams club": "samsclub.com",
    "aldi": "aldi.us",
    "sprouts": "sprouts.com",
    "wegmans": "wegmans.com",
    "heb": "heb.com",
    "h-e-b": "heb.com",
    "meijer": "meijer.com",
    "food lion": "foodlion.com",
    "stop & shop": "stopandshop.com",
    "giant": "giantfood.com",

    // Transport
    "uber": "uber.com",
    "uber ride": "uber.com",
    "lyft": "lyft.com",
    "lyft ride": "lyft.com",
    "waymo": "waymo.com",
    "caltrain": "caltrain.com",
    "caltrain ticket": "caltrain.com",
    "bart": "bart.gov",
    "metro": "metro.net",
    "mta": "mta.info",
    "amtrak": "amtrak.com",
    "delta": "delta.com",
    "united": "united.com",
    "american airlines": "aa.com",
    "southwest": "southwest.com",
    "jetblue": "jetblue.com",
    "alaska airlines": "alaskaair.com",
    "spirit": "spirit.com",
    "frontier": "flyfrontier.com",
    "zipcar": "zipcar.com",
    "turo": "turo.com",
    "bird": "bird.co",
    "lime": "li.me",

    // Fitness
    "equinox": "equinox.com",
    "peloton": "onepeloton.com",
    "headspace": "headspace.com",
    "calm": "calm.com",
    "duolingo": "duolingo.com",
    "strava": "strava.com",
    "planet fitness": "planetfitness.com",
    "planetfitness": "planetfitness.com",
    "24 hour fitness": "24hourfitness.com",
    "anytime fitness": "anytimefitness.com",
    "crossfit": "crossfit.com",
    "noom": "noom.com",
    "myfitnesspal": "myfitnesspal.com",
    "fitbod": "fitbod.me",
    "whoop": "whoop.com",
    "oura": "ouraring.com",
    "beachbody": "beachbody.com",
    "classpass": "classpass.com",
    "nike training": "nike.com",
    "apple fitness": "apple.com",
    "apple fitness+": "apple.com",

    // Shopping
    "amazon": "amazon.com",
    "target": "target.com",
    "walmart": "walmart.com",
    "apple": "apple.com",
    "best buy": "bestbuy.com",
    "bestbuy": "bestbuy.com",
    "nike": "nike.com",
    "adidas": "adidas.com",
    "zara": "zara.com",
    "h&m": "hm.com",
    "uniqlo": "uniqlo.com",
    "gap": "gap.com",
    "nordstrom": "nordstrom.com",
    "macy's": "macys.com",
    "macys": "macys.com",
    "ikea": "ikea.com",
    "etsy": "etsy.com",
    "ebay": "ebay.com",
    "wayfair": "wayfair.com",
    "chewy": "chewy.com",
    "petco": "petco.com",
    "petsmart": "petsmart.com",
    "home depot": "homedepot.com",
    "homedepot": "homedepot.com",
    "lowe's": "lowes.com",
    "lowes": "lowes.com",
    "cvs": "cvs.com",
    "walgreens": "walgreens.com",
    "rite aid": "riteaid.com",
    "sephora": "sephora.com",
    "ulta": "ulta.com",
    "old navy": "oldnavy.com",
    "banana republic": "bananarepublic.com",
    "j.crew": "jcrew.com",
    "jcrew": "jcrew.com",
    "anthropologie": "anthropologie.com",
    "urban outfitters": "urbanoutfitters.com",
    "asos": "asos.com",
    "shein": "shein.com",
    "fashion nova": "fashionnova.com",
    "lululemon": "lululemon.com",
    "patagonia": "patagonia.com",
    "rei": "rei.com",
    "under armour": "underarmour.com",

    // Gas & Utilities
    "shell": "shell.com",
    "shell gas": "shell.com",
    "chevron": "chevron.com",
    "bp": "bp.com",
    "exxon": "exxon.com",
    "mobil": "mobil.com",
    "arco": "arco.com",
    "76": "76.com",
    "circle k": "circlek.com",
    "7-eleven": "7-eleven.com",
    "7eleven": "7-eleven.com",
    "wawa": "wawa.com",
    "sheetz": "sheetz.com",
    "pg&e": "pge.com",
    "pg&e electric": "pge.com",
    "pg&e gas": "pge.com",
    "pge": "pge.com",
    "con edison": "coned.com",
    "conedison": "coned.com",
    "duke energy": "duke-energy.com",
    "at&t": "att.com",
    "verizon": "verizon.com",
    "comcast": "comcast.com",
    "xfinity": "xfinity.com",
    "t-mobile": "t-mobile.com",
    "tmobile": "t-mobile.com",
    "sprint": "sprint.com",
    "boost mobile": "boostmobile.com",
    "spectrum": "spectrum.com",
    "cox": "cox.com",
    "optimum": "optimum.com",

    // Finance & Banking
    "venmo": "venmo.com",
    "paypal": "paypal.com",
    "cashapp": "cash.app",
    "cash app": "cash.app",
    "robinhood": "robinhood.com",
    "coinbase": "coinbase.com",
    "chase": "chase.com",
    "bank of america": "bankofamerica.com",
    "wells fargo": "wellsfargo.com",
    "wellsfargo": "wellsfargo.com",
    "citi": "citibank.com",
    "citibank": "citibank.com",
    "capital one": "capitalone.com",
    "capitalone": "capitalone.com",
    "american express": "americanexpress.com",
    "amex": "americanexpress.com",
    "discover": "discover.com",
    "ally": "ally.com",
    "ally bank": "ally.com",
    "sofi": "sofi.com",
    "chime": "chime.com",
    "revolut": "revolut.com",
    "wise": "wise.com",
    "stripe": "stripe.com",
    "square": "squareup.com",
    "klarna": "klarna.com",
    "affirm": "affirm.com",
    "afterpay": "afterpay.com",
    "acorns": "acorns.com",
    "wealthfront": "wealthfront.com",
    "betterment": "betterment.com",
    "etrade": "etrade.com",
    "fidelity": "fidelity.com",
    "schwab": "schwab.com",
    "td ameritrade": "tdameritrade.com",
    "vanguard": "vanguard.com",
    "kraken": "kraken.com",
    "binance": "binance.com",
    "gemini": "gemini.com",

    // News & Reading
    "nytimes": "nytimes.com",
    "new york times": "nytimes.com",
    "wsj": "wsj.com",
    "wall street journal": "wsj.com",
    "medium": "medium.com",
    "substack": "substack.com",
    "the atlantic": "theatlantic.com",
    "washington post": "washingtonpost.com",
    "wapo": "washingtonpost.com",
    "bloomberg": "bloomberg.com",
    "economist": "economist.com",
    "wired": "wired.com",
    "buzzfeed": "buzzfeed.com",
    "huffpost": "huffpost.com",
    "axios": "axios.com",
    "politico": "politico.com",
    "reuters": "reuters.com",
    "ap news": "apnews.com",
    "kindle": "amazon.com",
    "scribd": "scribd.com",
    "goodreads": "goodreads.com",
    "libby": "overdrive.com",

    // AI & Tech
    "chatgpt": "openai.com",
    "openai": "openai.com",
    "claude": "anthropic.com",
    "anthropic": "anthropic.com",
    "midjourney": "midjourney.com",
    "dall-e": "openai.com",
    "perplexity": "perplexity.ai",
    "jasper": "jasper.ai",
    "copy.ai": "copy.ai",
    "1password": "1password.com",
    "lastpass": "lastpass.com",
    "dashlane": "dashlane.com",
    "bitwarden": "bitwarden.com",
    "nordvpn": "nordvpn.com",
    "expressvpn": "expressvpn.com",
    "surfshark": "surfshark.com",
    "mullvad": "mullvad.net",
    "patreon": "patreon.com",
    "gumroad": "gumroad.com",
    "teachable": "teachable.com",
    "skillshare": "skillshare.com",
    "masterclass": "masterclass.com",
    "coursera": "coursera.com",
    "udemy": "udemy.com",
    "linkedin learning": "linkedin.com",
    "linkedin": "linkedin.com",
    "codecademy": "codecademy.com",

    // Social & Communication
    "twitter": "twitter.com",
    "x": "x.com",
    "instagram": "instagram.com",
    "facebook": "facebook.com",
    "whatsapp": "whatsapp.com",
    "telegram": "telegram.org",
    "signal": "signal.org",
    "snapchat": "snapchat.com",
    "tiktok": "tiktok.com",
    "pinterest": "pinterest.com",
    "reddit": "reddit.com",
    "tumblr": "tumblr.com",
    "bereal": "bereal.com",

    // Travel & Hotels
    "airbnb": "airbnb.com",
    "vrbo": "vrbo.com",
    "booking.com": "booking.com",
    "booking": "booking.com",
    "hotels.com": "hotels.com",
    "expedia": "expedia.com",
    "kayak": "kayak.com",
    "hopper": "hopper.com",
    "tripadvisor": "tripadvisor.com",
    "hilton": "hilton.com",
    "marriott": "marriott.com",
    "hyatt": "hyatt.com",
    "ihg": "ihg.com",
    "wyndham": "wyndham.com",
    "enterprise": "enterprise.com",
    "hertz": "hertz.com",
    "avis": "avis.com",
    "budget": "budget.com",
    "national": "nationalcar.com",

    // Health & Wellness
    "hinge": "hinge.co",
    "tinder": "tinder.com",
    "bumble": "bumble.com",
    "match": "match.com",
    "eharmony": "eharmony.com",
    "teladoc": "teladoc.com",
    "hims": "hims.com",
    "hers": "hers.com",
    "roman": "ro.co",
    "weight watchers": "weightwatchers.com",
    "ww": "weightwatchers.com",
    "one medical": "onemedical.com",
    "oscar": "hioscar.com",
    "cigna": "cigna.com",
    "aetna": "aetna.com",
    "bluecross": "bcbs.com",
    "blue cross": "bcbs.com",
    "cvs health": "cvshealth.com",
    "walgreens health": "walgreens.com",
]

// Category fallback icons
let categoryFallbackIcons: [String: String] = [
    "Dining": "fork.knife",
    "Transport": "car.fill",
    "Shopping": "bag.fill",
    "Entertainment": "gamecontroller.fill",
    "Groceries": "cart.fill",
    "Utilities": "bolt.fill",
    "Fitness": "dumbbell.fill",
    "Subscriptions": "music.note",
    "Lifestyle": "cup.and.saucer.fill",
    "Other": "ellipsis.circle.fill",
]

func brandLogoURL(for name: String) -> URL? {
    let key = name.lowercased().trimmingCharacters(in: .whitespaces)

    // Only look up known brands — no guessing
    if let domain = brandDomains[key] {
        return URL(string: "https://www.google.com/s2/favicons?domain=\(domain)&sz=128")
    }

    // Try first word match — "Spotify Premium" → "spotify"
    let firstWord = key.components(separatedBy: " ").first ?? key
    if let domain = brandDomains[firstWord] {
        return URL(string: "https://www.google.com/s2/favicons?domain=\(domain)&sz=128")
    }

    // Unknown — return nil, show nothing
    return nil
}

struct BrandLogoView: View {
    let name: String
    let size: CGFloat
    let fallbackIcon: String
    let fallbackColor: Color
    var showFallback: Bool = false

    @State private var debouncedName = ""
    @State private var debounceTask: Task<Void, Never>? = nil

    var body: some View {
        Group {
            if debouncedName.isEmpty {
                Color.clear
            } else {
                AsyncImage(url: brandLogoURL(for: debouncedName)) { phase in
                    switch phase {
                    case .success(let image):
                        image
                            .resizable()
                            .scaledToFit()
                            .frame(width: size * 0.62, height: size * 0.62)
                            .clipShape(RoundedRectangle(cornerRadius: size * 0.12))
                    default:
                        if showFallback {
                            Image(systemName: fallbackIcon)
                                .font(.system(size: size * 0.38, weight: .medium))
                                .foregroundColor(fallbackColor)
                        } else {
                            Color.clear
                        }
                    }
                }
            }
        }
        .onAppear {
            debouncedName = name
        }
        .onChange(of: name) { _, newValue in
            // Cancel previous debounce and start a new one
            debounceTask?.cancel()
            debounceTask = Task { @MainActor in
                try? await Task.sleep(nanoseconds: 600_000_000) // 600ms
                guard !Task.isCancelled else { return }
                debouncedName = newValue.trimmingCharacters(in: .whitespaces)
            }
        }
        .onDisappear {
            debounceTask?.cancel()
            debounceTask = nil
        }
    }
}
